# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = ""
name = "Store Credit Discounts"
application_url = ""
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = ""
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_discounts,unauthenticated_read_customers,write_discounts"

[auth]
redirect_urls = []

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
